#datasource specific properties
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecomproductdb
    username: root
    password: Tiger

#jpa specific properties

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
 
#add driver name while using docker